live_config_reload = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 10.5
offset = { y = 2 }

[cursor]
style = { shape = "Block", blinking = "On" }

[window]
decorations = "None"

[mouse]
hide_when_typing = true

[terminal]
osc52 = "CopyPaste"

[colors]
  [colors.primary]
    background = "#282828"
    foreground = "#ebdbb2"

  [colors.cursor]
    text = "#282828"
    cursor = "#ebdbb2"

  [colors.normal]
    black   = "#282828"
    red     = "#cc241d"
    green   = "#98971a"
    yellow  = "#d79921"
    blue    = "#458588"
    magenta = "#b16286"
    cyan    = "#689d6a"
    white   = "#a89984"

  [colors.bright]
    black   = "#928374"
    red     = "#fb4934"
    green   = "#b8bb26"
    yellow  = "#fabd2f"
    blue    = "#83a598"
    magenta = "#d3869b"
    cyan    = "#8ec07c"
    white   = "#ebdbb2"

  [colors.selection]
    text = "#282828"
    background = "#d79921"
