live_config_reload = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono" }
size = 10
offset = { y = 2 }

[cursor]
style = { shape = "Block", blinking = "On" }

[window]
decorations = "None"

[mouse]
hide_when_typing = true

[terminal]
osc52 = "CopyPaste"
